server:
  port: 0  # porta dinamica
  servlet:
    context-path: /ms-kotlin

spring:
  application:
    name: ms-kotlin
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:catalogo}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:catalogo}
    password: ${MYSQL_PASSWORD:catalogo}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${random.uuid}
        health-check-path: /ms-kotlin/actuator/health
        health-check-interval: 10s
        metadata:
          deregister-critical-service-after: 1m

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /
