server:
  port: ${SERVER_PORT:${PORT:0}}  # usa porta dinâmica por padrão
  servlet:
    context-path: /ms-kotlin

spring:
  application:
    name: ms-kotlin
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:./catalogo.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1 # SQLite permite apenas uma escrita por vez
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${random.uuid}
        health-check-path: /ms-kotlin/actuator/health
        health-check-interval: 10s
        metadata:
          deregister-critical-service-after: 1m

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /
